name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Apt install system dependencies (linux)
      if: ${{ startsWith(matrix.platform, 'ubuntu-') }}
      run: |
        echo "::group::Run sudo apt-get update"
        sudo apt-get update
        echo "::endgroup::"
        echo "::group::Run sudo apt-get install graphviz"
        sudo apt-get install graphviz
        echo "::endgroup::"
        echo "::group::Run dot -V"
        DOT_VERSION="$(dot -V 2>&1)"
        echo $DOT_VERSION;
        echo "::endgroup::"
        echo "::notice::Apt installed ${DOT_VERSION#dot - }"
      shell: bash

    - name: Brew install system dependencies (macos)
      if: ${{ startsWith(matrix.platform, 'macos-')}}
      run: |
        echo "::group::Run brew update --preinstall"
        brew update --preinstall
        echo "::endgroup::"
        echo "::group::Run brew install graphviz"
        brew install graphviz
        echo "::endgroup::"
        echo "::group::Run dot -V"
        DOT_VERSION="$(dot -V 2>&1)"
        echo $DOT_VERSION
        echo "::endgroup::"
        echo "::notice::Brew installed ${DOT_VERSION#dot - }"
      shell: bash

    - name: Choco install system dependencies (windows)
      if: ${{ startsWith(matrix.platform, 'windows-') }}
      run: |
        echo "::group::Run choco install --no-progress graphviz"
        choco install --no-progress graphviz
        echo "::endgroup::"
        echo "::group::Run dot -V"
        DOT_VERSION="$(dot -V 2>&1)"
        echo $DOT_VERSION
        echo "::endgroup::"
        echo "::notice::Choco installed ${DOT_VERSION#dot - }"
      shell: bash

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools biopython numpy pydot

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: |
        cd tests
        python -m pytest
